name: CI

on:
  push:
    branches:
      - master

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bendit tool
      run: pip install bandit

    - name: Run Bandit scan
      run: bandit -ll -ii -r .