name: CI

on:
  push:
    branches:
      - master

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bendit tool
      run: pip install bandit

    - name: Run Bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Builld Image and run Image scan
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v2

    - name: Setup docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout scan
      run: |
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
        docker scout quickview
        docker scout cves